all:
  hosts:
     node01:
       ansible_host: 10.32.101.209
       ansible_user: vagrant

     node02:
       ansible_host: 172.10.0.35
       ansible_user: vagrant
       ansible_ssh_pass: vagrant
     node03:
       ansible_host: 10.32.101.86
       ansible_user: vagrant

     amq:
       ansible_host: 172.10.0.37
       ansible_user: vagrant
       ansible_ssh_pass: vagrant

     cent7:
       ansible_host: 172.10.0.38
       ansible_user: admin
